# This macro is used to properly set up the interactive session (GUI)

/vis/open OGLSQt
/vis/ogl/set/eventsDrawInterval 999999       # To be updated with Geant4 10.3 (probably)

/gui/addMenu vis Visualization
/gui/addButton vis "Draw Axes" "/vis/scene/add/axes 0 0 0 10 cm"

/gui/addMenu run Run
/gui/addButton run "Beam On (1)" "/run/beamOn 1"
/gui/addButton run "Beam On (10)" "/run/beamOn 10"
/gui/addButton run "Beam On (100)" "/run/beamOn 100"
/gui/addButton run "Beam On (1000)" "/run/beamOn 1000"
/gui/addButton run "Beam On (10000)" "/run/beamOn 10000"

/run/initialize
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/vis/viewer/flush

/gps/pos/type Beam
/gps/pos/sigma_r 5 mm

/gps/ene/type Gauss

# initialize for 250 MeV run
/run/initialize
/gps/ene/mono 250 MeV
/gps/ene/sigma 1 MeV
